# Generated by Django 4.1.3 on 2022-11-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="user_name",
            new_name="username",
        ),
    ]
